AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaFunction:
    Type: String
    Description: enter the lambda funtion name
  Triggers:
    Type: String
    Default: SQS
    AllowedValues:
      - AlqxaHome 
      - SQS
      - SNS
    Description: Select Trigger type
  TriggerName:
    Type: String
    Description: enter Trigger api name
Conditions:
  CreateSQSTrigger: !Equals [!Ref Triggers, SQS]
  CreateSNSTrigger: !Equals [!Ref Triggers, SNS]
  CreateAlqxaHomeTrigger: !Equals [!Ref Triggers, AlqxaHome]

Resources:
  LambdaSNS:
    Type: "AWS::Lambda::Permission"
    Condition: CreateSNSTrigger
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
      Principal: "sns.amazonaws.com"
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TriggerName}"
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: CreateSQSTrigger
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${TriggerName}"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
#  AlexaTrigger:
#    Type: "AWS::Lambda::Permission"
#    Condition: CreateAlqxaHomeTrigger
#    Properties:
#      Action: lambda:InvokeFunction
#      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
#      Principal: alexa-appkit.amazon.com
#      event-source-token:
