AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Triggers:
    Type: String
    Default: SQS
    AllowedValues:
      - AlqxaHome 
      - SQS
      - SNS
Conditions:
  CreateSQSTrigger: !Equals [!Ref Triggers, SQS]
  CreateSNSTrigger: !Equals [!Ref Triggers, SNS]
  CreateAlqxaHomeTrigger: !Equals [!Ref Triggers, AlqxaHome]

Resources:
  LambdaSNS:
    Type: "AWS::Lambda::Permission"
    Condition: CreateSNSTrigger
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:<Lambda function Name>"
      Principal: "sns.amazonaws.com"
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:<SNS Topic Name>"
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: CreateSQSTrigger
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tests"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:<lambda Function Name>"
#  AlexaTrigger:
#    Type: "AWS::Lambda::Permission"
#    Condition: CreateAlqxaHomeTrigger
#    Properties:
#      Action: lambda:InvokeFunction
#      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambdaforApi"
#      Principal: alexa-appkit.amazon.com
#      event-source-token:
