AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: seleect the key pair
  Triggers:
    Type: String
    Default: SQS
    AllowedValues:
      - AlqxaHome 
      - SQS
      - SNS
  Lambdaarn:
    Type: AWS::Serverless::Function::FunctionName
    Description: seleect the lambda
Conditions:
  CreateSQSTrigger: !Equals [!Ref Triggers, SQS]
  CreateSNSTrigger: !Equals [!Ref Triggers, SNS]
  CreateAlqxaHomeTrigger: !Equals [!Ref Triggers, AlqxaHome]

Resources:
  LambdaSNS:
    Type: "AWS::Lambda::Permission"
    Condition: CreateSNSTrigger
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambdaforApi"
      Principal: "sns.amazonaws.com"
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:s3_bucket"
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: CreateSQSTrigger
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tests"
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambdaforApi"
#  AlexaTrigger:
#    Type:
#    Condition:
#    Properties:
#      Action: lambda:InvokeFunction
#      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambdaforApi"
#      Principal: alexa-appkit.amazon.com
#      event-source-token:
